// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RitsuPi.EmailOps.Infrastructure.Database;

#nullable disable

namespace RitsuPi.EmailOps.Infrastructure.Migrations
{
    [DbContext(typeof(RitsuOpsContext))]
    [Migration("20250604025337_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RitsuPi.EmailOps.Domain.Entities.EmailHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<Guid>("SemanticKernelHistoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("semantic_kernel_history_id");

                    b.HasKey("Id")
                        .HasName("pk_email_histories");

                    b.HasIndex("SemanticKernelHistoryId")
                        .HasDatabaseName("ix_email_histories_semantic_kernel_history_id");

                    b.ToTable("email_histories", (string)null);
                });

            modelBuilder.Entity("RitsuPi.EmailOps.Domain.Entities.SemanticKernelHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("MemoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_json");

                    b.Property<string>("ThreadHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("thread_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_message_threads");

                    b.HasIndex("ThreadHash")
                        .IsUnique()
                        .HasDatabaseName("ix_message_threads_thread_hash");

                    b.ToTable("message_threads", (string)null);
                });

            modelBuilder.Entity("RitsuPi.EmailOps.Domain.Entities.EmailHistory", b =>
                {
                    b.HasOne("RitsuPi.EmailOps.Domain.Entities.SemanticKernelHistory", "SemanticKernelHistory")
                        .WithMany("EmailHistories")
                        .HasForeignKey("SemanticKernelHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_histories_message_threads_semantic_kernel_history_id");

                    b.Navigation("SemanticKernelHistory");
                });

            modelBuilder.Entity("RitsuPi.EmailOps.Domain.Entities.SemanticKernelHistory", b =>
                {
                    b.Navigation("EmailHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
